data-platform #17: modify make-installer script to move existing ~/data-platform directory and installer zip

diff --git a/scripts/make-installer b/scripts/make-installer
--- a/scripts/make-installer
+++ b/scripts/make-installer
@@ -114,3 +114,7 @@ echo "created TAR_FILE $TAR_FILE"
 gzip "$TAR_FILE"
 echo "created tarball $TAR_FILE.gz"
 
+# move target directory to add timestamp suffix
+TIMESTAMP=$(date '+%s')
+mv "$TARGET_DIR" "$TARGET_DIR.$TIMESTAMP" ||  { echo "failed to mv $TARGET_DIR to $TARGET_DIR.$TIMESTAMP"; exit 1; }
+echo "moved $TARGET_DIR to $TARGET_DIR.$TIMESTAMP"
